name: kontrakan
services:
  kontrakan:
    container_name: kontrakan
    image: kontrakan:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://kontrakan:kontrakan123@host.docker.internal:5432/kontrakan
      UPLOAD_DIR: /data/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - kontrakan_uploads:/data/uploads
    labels:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/nextjs.png
    x-casaos:
      architectures:
        - amd64
      main: kontrakan
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/nextjs.png
      title:
        en_US: Achi Kosan
        id_ID: Achi Kosan
      category: Web
      description:
        en_US: Landing page & admin panel kosan (Next.js + Postgres lokal)
        id_ID: Landing page & admin panel kosan (Next.js + Postgres lokal)
      tagline:
        en_US: Landing page kosan
        id_ID: Landing page kosan
      author: farhankhuwais
      developer: farhankhuwais
      store_app_id: kontrakan
volumes:
  kontrakan_uploads:
